/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    YourContract: {
      address: "0xed1db453c3156ff3155a97ad217b3087d5dc5f6e",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_owner",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "receive",
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "greeting",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "premium",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "setGreeting",
          inputs: [
            {
              name: "_newGreeting",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "totalCounter",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "userGreetingCounter",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "withdraw",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "GreetingChange",
          inputs: [
            {
              name: "greetingSetter",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newGreeting",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "premium",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
            {
              name: "value",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 251,
    },
    Paypink: {
      address: "0x12975173b87f7595ee45dffb2ab812ece596bf84",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_paymentToken",
              type: "address",
              internalType: "address",
            },
            {
              name: "_priceFeed",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "authorizedX402Caller",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "creatorBalances",
          inputs: [
            {
              name: "creator",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "balance",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "creatorTokenBalances",
          inputs: [
            {
              name: "creator",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "balance",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getArticle",
          inputs: [
            {
              name: "slug",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct Paypink.Article",
              components: [
                {
                  name: "slug",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "creator",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "price",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "contentHash",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "views",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "earned",
                  type: "uint256",
                  internalType: "uint256",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getArticlePriceInEth",
          inputs: [
            {
              name: "slug",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getCreatorArticles",
          inputs: [
            {
              name: "creator",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes32[]",
              internalType: "bytes32[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getCreatorBalance",
          inputs: [
            {
              name: "creator",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "hasPaid",
          inputs: [
            {
              name: "slugHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "reader",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "paid",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "maxStaleness",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "ownerBalance",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "payForArticle",
          inputs: [
            {
              name: "slug",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "paymentToken",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "platformTokenBalance",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "priceFeed",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract AggregatorV3Interface",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "recordX402Payment",
          inputs: [
            {
              name: "slug",
              type: "string",
              internalType: "string",
            },
            {
              name: "reader",
              type: "address",
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "registerArticle",
          inputs: [
            {
              name: "slug",
              type: "string",
              internalType: "string",
            },
            {
              name: "price",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "contentHash",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setAuthorizedX402Caller",
          inputs: [
            {
              name: "_caller",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setMaxStaleness",
          inputs: [
            {
              name: "_maxStaleness",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setPaymentToken",
          inputs: [
            {
              name: "_token",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setPriceFeed",
          inputs: [
            {
              name: "_feed",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "tipByAddress",
          inputs: [
            {
              name: "creator",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "tipBySlug",
          inputs: [
            {
              name: "slug",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "withdraw",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "withdrawPlatformFees",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "withdrawPlatformTokenFees",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "withdrawTokens",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "ArticlePaid",
          inputs: [
            {
              name: "key",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "reader",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ArticleRegistered",
          inputs: [
            {
              name: "key",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "creator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "slug",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "price",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ArticleTipped",
          inputs: [
            {
              name: "key",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "creator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "slug",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "tip",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "AuthorizedX402CallerSet",
          inputs: [
            {
              name: "oldCaller",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newCaller",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "CreatorTipped",
          inputs: [
            {
              name: "creator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "tip",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "MaxStalenessUpdated",
          inputs: [
            {
              name: "oldStaleness",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "newStaleness",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "PaymentTokenUpdated",
          inputs: [
            {
              name: "oldToken",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newToken",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "PriceFeedUpdated",
          inputs: [
            {
              name: "oldFeed",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newFeed",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "X402PaymentRecorded",
          inputs: [
            {
              name: "key",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "reader",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "Paypink__AlreadyPaid",
          inputs: [],
        },
        {
          type: "error",
          name: "Paypink__ArticleNotFound",
          inputs: [],
        },
        {
          type: "error",
          name: "Paypink__InsufficientPayment",
          inputs: [
            {
              name: "required",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "sent",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "Paypink__InvalidAddress",
          inputs: [],
        },
        {
          type: "error",
          name: "Paypink__InvalidPrice",
          inputs: [],
        },
        {
          type: "error",
          name: "Paypink__InvalidPriceFeedDecimals",
          inputs: [],
        },
        {
          type: "error",
          name: "Paypink__InvalidStaleness",
          inputs: [],
        },
        {
          type: "error",
          name: "Paypink__NothingToWithdraw",
          inputs: [],
        },
        {
          type: "error",
          name: "Paypink__OwnerOnly",
          inputs: [],
        },
        {
          type: "error",
          name: "Paypink__SlugTaken",
          inputs: [],
        },
        {
          type: "error",
          name: "Paypink__StalePrice",
          inputs: [],
        },
        {
          type: "error",
          name: "Paypink__UnauthorizedCaller",
          inputs: [],
        },
        {
          type: "error",
          name: "Paypink__Withdraw_FailedToSend",
          inputs: [],
        },
        {
          type: "error",
          name: "SafeERC20FailedOperation",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 252,
    },
    MockV3Aggregator: {
      address: "0xf7cd8fa9b94db2aa972023b379c7f72c65e4de9d",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_decimals",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "_initialAnswer",
              type: "int256",
              internalType: "int256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "answer",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "int256",
              internalType: "int256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "decimals",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "description",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "latestRoundData",
          inputs: [],
          outputs: [
            {
              name: "roundId_",
              type: "uint80",
              internalType: "uint80",
            },
            {
              name: "answer_",
              type: "int256",
              internalType: "int256",
            },
            {
              name: "startedAt_",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "updatedAt_",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "answeredInRound_",
              type: "uint80",
              internalType: "uint80",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "roundId",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint80",
              internalType: "uint80",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "updateAnswer",
          inputs: [
            {
              name: "_answer",
              type: "int256",
              internalType: "int256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "updateRoundData",
          inputs: [
            {
              name: "_answer",
              type: "int256",
              internalType: "int256",
            },
            {
              name: "_updatedAt",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "updatedAt",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "version",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "pure",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 252,
    },
  },
  763373: {
    YourContract: {
      address: "0xdaac0a470381eebaaf8c63db47f2411b57832d9b",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_owner",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "receive",
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "greeting",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "premium",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "setGreeting",
          inputs: [
            {
              name: "_newGreeting",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "totalCounter",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "userGreetingCounter",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "withdraw",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "GreetingChange",
          inputs: [
            {
              name: "greetingSetter",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newGreeting",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "premium",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
            {
              name: "value",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 42035761,
    },
    Paypink: {
      address: "0x03b0f18148657395427ebe80c3eab9161153a426",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_paymentToken",
              type: "address",
              internalType: "address",
            },
            {
              name: "_priceFeed",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "authorizedX402Caller",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "creatorBalances",
          inputs: [
            {
              name: "creator",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "balance",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "creatorTokenBalances",
          inputs: [
            {
              name: "creator",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "balance",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getArticle",
          inputs: [
            {
              name: "slug",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct Paypink.Article",
              components: [
                {
                  name: "slug",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "creator",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "price",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "contentHash",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "views",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "earned",
                  type: "uint256",
                  internalType: "uint256",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getArticlePriceInEth",
          inputs: [
            {
              name: "slug",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getCreatorArticles",
          inputs: [
            {
              name: "creator",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes32[]",
              internalType: "bytes32[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getCreatorBalance",
          inputs: [
            {
              name: "creator",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "hasPaid",
          inputs: [
            {
              name: "slugHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "reader",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "paid",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "maxStaleness",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "ownerBalance",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "payForArticle",
          inputs: [
            {
              name: "slug",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "paymentToken",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "platformTokenBalance",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "priceFeed",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract AggregatorV3Interface",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "recordX402Payment",
          inputs: [
            {
              name: "slug",
              type: "string",
              internalType: "string",
            },
            {
              name: "reader",
              type: "address",
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "registerArticle",
          inputs: [
            {
              name: "slug",
              type: "string",
              internalType: "string",
            },
            {
              name: "price",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "contentHash",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setAuthorizedX402Caller",
          inputs: [
            {
              name: "_caller",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setMaxStaleness",
          inputs: [
            {
              name: "_maxStaleness",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setPaymentToken",
          inputs: [
            {
              name: "_token",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setPriceFeed",
          inputs: [
            {
              name: "_feed",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "tipByAddress",
          inputs: [
            {
              name: "creator",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "tipBySlug",
          inputs: [
            {
              name: "slug",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "withdraw",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "withdrawPlatformFees",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "withdrawPlatformTokenFees",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "withdrawTokens",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "ArticlePaid",
          inputs: [
            {
              name: "key",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "reader",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ArticleRegistered",
          inputs: [
            {
              name: "key",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "creator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "slug",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "price",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ArticleTipped",
          inputs: [
            {
              name: "key",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "creator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "slug",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "tip",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "AuthorizedX402CallerSet",
          inputs: [
            {
              name: "oldCaller",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newCaller",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "CreatorTipped",
          inputs: [
            {
              name: "creator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "tip",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "MaxStalenessUpdated",
          inputs: [
            {
              name: "oldStaleness",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "newStaleness",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "PaymentTokenUpdated",
          inputs: [
            {
              name: "oldToken",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newToken",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "PriceFeedUpdated",
          inputs: [
            {
              name: "oldFeed",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newFeed",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "X402PaymentRecorded",
          inputs: [
            {
              name: "key",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "reader",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "Paypink__AlreadyPaid",
          inputs: [],
        },
        {
          type: "error",
          name: "Paypink__ArticleNotFound",
          inputs: [],
        },
        {
          type: "error",
          name: "Paypink__InsufficientPayment",
          inputs: [
            {
              name: "required",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "sent",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "Paypink__InvalidAddress",
          inputs: [],
        },
        {
          type: "error",
          name: "Paypink__InvalidPrice",
          inputs: [],
        },
        {
          type: "error",
          name: "Paypink__InvalidPriceFeedDecimals",
          inputs: [],
        },
        {
          type: "error",
          name: "Paypink__InvalidStaleness",
          inputs: [],
        },
        {
          type: "error",
          name: "Paypink__NothingToWithdraw",
          inputs: [],
        },
        {
          type: "error",
          name: "Paypink__OwnerOnly",
          inputs: [],
        },
        {
          type: "error",
          name: "Paypink__SlugTaken",
          inputs: [],
        },
        {
          type: "error",
          name: "Paypink__StalePrice",
          inputs: [],
        },
        {
          type: "error",
          name: "Paypink__UnauthorizedCaller",
          inputs: [],
        },
        {
          type: "error",
          name: "Paypink__Withdraw_FailedToSend",
          inputs: [],
        },
        {
          type: "error",
          name: "SafeERC20FailedOperation",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 42035761,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
