name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  foundry-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Install foundry-toolchain
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: 1.5.1

      - name: Run forge tests
        working-directory: packages/foundry
        run: forge test -vvv

      - name: Run forge coverage
        working-directory: packages/foundry
        run: forge coverage

      - name: Generate LCOV report
        working-directory: packages/foundry
        run: forge coverage --report lcov

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: lcov-report
          path: packages/foundry/lcov.info

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: packages/foundry/lcov.info
