name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  foundry-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Install foundry-toolchain
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: 1.5.1

      - name: Run forge tests
        working-directory: packages/foundry
        run: forge test -vvv
